### ISSUE TITLE
The following modules are missing or built with a different engine version:

### ISSUE THREAD

**Issue by Contestant0star** [modio/UE4Plugin#41]
Using Unreal Engine 4.25 and used the plugin from "modio-0.5.2-ue425.zip"

The following modules are missing or built with a different engine version:

modio
Int64
modioEditor
Int64Editor

Engine modules cannot be compiled at runtime. Please build through your IDE.

**Comment by MarkusRannare** [comment]
Are you using this with a blueprint only or a c++ plugin? These files are intented for consumption only by C++ only projects where you need to compile it yourself.

If you want to use the plugin in a BP-only setup, I recommend you to use this:
https://www.unrealengine.com/marketplace/en-US/product/mod-browser-manager
Is that release but with the executables compiled.

I'll make sure to make a note in the release from now on to ensure that no one else are having the same issue

**Comment by MarkusRannare** [comment]
Hi, I haven't heard back from you in almost two weeks. Did my earlier question help you? If I don't hear anything from you before end of week I'll close the issue

**Comment by Contestant0star** [comment]
> Hi, I haven't heard back from you in almost two weeks. Did my earlier question help you? If I don't hear anything from you before end of week I'll close the issue

I just didn't reply since most of my project is blueprint only
